package:
  name: imbalanced-learn
  version: "0.1.1"

source:
  git_rev: 0.1.1
  git_url: https://github.com/fmfn/UnbalancedDataset.git

requirements:
  build:
    - python
    - setuptools
    - numpy
    - scipy
    - scikit-learn
  run:
    - python
    - numpy
    - scipy
    - scikit-learn

test:
  requires:
    - nose
    - coverage
  imports:
    - imblearn

about:
  home: https://github.com/fmfn/UnbalancedDataset
  license: MIT
  license_file: LICENSE

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
